tga2dds.exe -i background.tga -o .
tga2dds.exe -i background_ddn.tga -o .
tga2dds.exe -i background_ddn.tif -o .
tga2dds.exe -i chain_texture.tga -o .
tga2dds.exe -i chain_texture_ddn.tga -o .
tga2dds.exe -i chain_texture_mask.tga -o .
tga2dds.exe -i lion.tga -o .
tga2dds.exe -i lion2_ddn.tga -o .
tga2dds.exe -i lion_ddn.tga -o .
tga2dds.exe -i spnza_bricks_a_ddn.tga -o .
tga2dds.exe -i spnza_bricks_a_diff.tga -o .
tga2dds.exe -i spnza_bricks_a_spec.tga -o .
tga2dds.exe -i sponza_arch_ddn.tga -o .
tga2dds.exe -i sponza_arch_diff.tga -o .
tga2dds.exe -i sponza_arch_spec.tga -o .
tga2dds.exe -i sponza_ceiling_a_diff.tga -o .
tga2dds.exe -i sponza_ceiling_a_spec.tga -o .
tga2dds.exe -i sponza_column_a_ddn.tga -o .
tga2dds.exe -i sponza_column_a_diff.tga -o .
tga2dds.exe -i sponza_column_a_spec.tga -o .
tga2dds.exe -i sponza_column_b_ddn.tga -o .
tga2dds.exe -i sponza_column_b_diff.tga -o .
tga2dds.exe -i sponza_column_b_spec.tga -o .
tga2dds.exe -i sponza_column_c_ddn.tga -o .
tga2dds.exe -i sponza_column_c_diff.tga -o .
tga2dds.exe -i sponza_column_c_spec.tga -o .
tga2dds.exe -i sponza_curtain_blue_diff.tga -o .
tga2dds.exe -i sponza_curtain_diff.tga -o .
tga2dds.exe -i sponza_curtain_green_diff.tga -o .
tga2dds.exe -i sponza_details_diff.tga -o .
tga2dds.exe -i sponza_details_spec.tga -o .
tga2dds.exe -i sponza_fabric_blue_diff.tga -o .
tga2dds.exe -i sponza_fabric_diff.tga -o .
tga2dds.exe -i sponza_fabric_green_diff.tga -o .
tga2dds.exe -i sponza_fabric_spec.tga -o .
tga2dds.exe -i sponza_flagpole_diff.tga -o .
tga2dds.exe -i sponza_flagpole_spec.tga -o .
tga2dds.exe -i sponza_floor_a_diff.tga -o .
tga2dds.exe -i sponza_floor_a_spec.tga -o .
tga2dds.exe -i sponza_roof_diff.tga -o .
tga2dds.exe -i sponza_thorn_ddn.tga -o .
tga2dds.exe -i sponza_thorn_diff.tga -o .
tga2dds.exe -i sponza_thorn_mask.tga -o .
tga2dds.exe -i sponza_thorn_spec.tga -o .
tga2dds.exe -i vase_ddn.tga -o .
tga2dds.exe -i vase_dif.tga -o .
tga2dds.exe -i vase_hanging.tga -o .
tga2dds.exe -i vase_plant.tga -o .
tga2dds.exe -i vase_plant_mask.tga -o .
tga2dds.exe -i vase_plant_spec.tga -o .
tga2dds.exe -i vase_round.tga -o .
tga2dds.exe -i vase_round_ddn.tga -o .
tga2dds.exe -i vase_round_spec.tga -o .
